version: 0.1
database:
  uri: "postgres://quack:pass@postgres:5432/quack"
  name: "quack"
  exclude:
    - "users"
    - "goose_migrations"
    - "goose_db_version"
models:
  path: "misc/models"
  exclude:
    - "Base"
    - "Users"
    - "AuthUsers"
migrations:
  path: "misc/migrations"
