version: 0.1
database:
  uri: "postgres://stexp:1!password!2@postgres:5432/stexp"
  name: "stexp"
  exclude:
    - "auth_users"
    - "users"
    - "goose_migrations"
models:
  path: "models"
  exclude:
    - "Base"
    - "Users"
    - "AuthUsers"
migrations:
  path: "migrations"
