package models

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	uuid "github.com/satori/go.uuid"
)

type TestTableA struct {
	Base
	Name     string
	Email    *string `gorm:"type:varchar(255)"`
	Age      uint8
	Birthday *time.Time
	Context  string   `gorm:"type:varchar(100);null"`
	Sid      uint     `gorm:"not null;default:0"`
	Salt     string   `gorm:"type:text;null"`
	Tags     []string `gorm:"type:text[]"`
}

type TestTableB struct {
	ID        uint `gorm:"type:serial;primaryKey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time `gorm:"null"`
	Sid       uuid.UUID `gorm:"default:gen_random_uuid()"`
	Prec      float32   `gorm:"null"`
	Height    int16     `gorm:"null"`
	Em        int
}

type TestTableC struct {
	ID        uint              `gorm:"type:bigint;default:GENERATED BY DEFAULT AS IDENTITY;primaryKey"`
	Data      pgtype.JSONCodec  `gorm:"type:json;default:'{}';not null"`
	Tasks     pgtype.JSONBCodec `gorm:"type:jsonb;default:'{}';not null"`
	Colors    []int             `gorm:"type:integer[];default:'{}'"`
	CreatedAt time.Time         `gorm:"type:timestamp without time zone;not null;default:now();<-:create"`
	UpdatedAt time.Time         `gorm:"type:timestamp without time zone;not null;default:now();<-:update"`
	DeletedAt time.Time         `gorm:"type:timestamp without time zone;null"`
}
