package models

import (
	"time"
)

type TestTableA struct {
	Base
}

type TestTableB struct {
	ID        uint `gorm:"type:serial;primaryKey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time `gorm:"null"`
}

type TestTableC struct {
	ID        uint      `gorm:"type:bigint;default:GENERATED BY DEFAULT AS IDENTITY;primaryKey"`
	CreatedAt time.Time `gorm:"type:timestamp without time zone;not null;default:now();<-:create"`
	UpdatedAt time.Time `gorm:"type:timestamp without time zone;not null;default:now();<-:update"`
	DeletedAt time.Time `gorm:"type:timestamp without time zone;null"`
}
