package models

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	uuid "github.com/satori/go.uuid"
)

type TestTableA struct {
	Base
	Name     string
	Email    *string `gorm:"type:varchar(255)"`
	Age      uint32
	Birthday *time.Time `gorm:"index:idx_tta_date_birth,type:btree,expression:DATE(birthday)"`
	Context  string     `gorm:"type:varchar(255);not null"`
	Sid      uint       `gorm:"not null;default:100;index:idx_tta_where_sid,where:sid<100"`
	Salt     string     `gorm:"type:text;null"`
	Tags     []string   `gorm:"type:text[];default:'{}'"`
}

type TestTableB struct {
	ID        uint `gorm:"type:serial;primaryKey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time `gorm:"null;index:,unique,options:NULLS NOT DISTINCT"`
	Sid       uuid.UUID `gorm:"default:gen_random_uuid()"`
	Prec      float32   `gorm:"not null;default:0.002;index:idx_ttb_float,type:hash"`
	Height    int16     `gorm:"null;index:idx_ttb_height_em,sort:desc,type:btree,priority:1"`
	Em        int8      `gorm:"null;index:idx_ttb_height_em,sort:desc,type:btree,priority:2"`
}

type TestTableC struct {
	ID        uint              `gorm:"type:bigint;default:GENERATED BY DEFAULT AS IDENTITY;primaryKey"`
	Data      pgtype.JSONCodec  `gorm:"type:json;default:'{}';not null"`
	Tasks     pgtype.JSONBCodec `gorm:"type:jsonb;default:'{}';not null"`
	Colors    []int             `gorm:"type:integer[];default:'{}'"`
	CreatedAt time.Time         `gorm:"type:timestamp without time zone;not null;default:now();<-:create"`
	UpdatedAt time.Time         `gorm:"type:timestamp without time zone;not null;default:now();<-:update"`
	DeletedAt time.Time         `gorm:"type:timestamp without time zone;null"`
}
