-- +goose Up
CREATE TABLE "public"."test_table_a"(
	id uuid NOT NULL default gen_random_uuid(),
	created_at timestamp without time zone NOT NULL default now(),
	updated_at timestamp without time zone NOT NULL default now(),
	PRIMARY KEY ("id")
);
CREATE TABLE "public"."test_table_b"(
	id serial NOT NULL,
	created_at timestamp without time zone NOT NULL,
	updated_at timestamp without time zone NOT NULL,
	deleted_at timestamp without time zone,
	PRIMARY KEY ("id")
);
CREATE TABLE "public"."test_table_c"(
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	created_at timestamp without time zone NOT NULL default now(),
	updated_at timestamp without time zone NOT NULL default now(),
	deleted_at timestamp without time zone,
	PRIMARY KEY ("id")
);

-- +goose Down
DROP TABLE IF EXISTS "public"."test_table_a";
DROP TABLE IF EXISTS "public"."test_table_b";
DROP TABLE IF EXISTS "public"."test_table_c";
